# Generated by Django 3.0 on 2023-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
